name: todo_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
    sdk: "^3.1.0"

dependencies:
    dynamic_color: ^1.6.6
    extension_google_sign_in_as_googleapis_auth: ^2.0.10
    firebase_core: ^2.15.1
    flutter:
        sdk: flutter
    flutter_adaptive_scaffold: ^0.1.6
    google_fonts: ^5.1.0
    google_sign_in: ^6.1.4
    googleapis: ^11.4.0
    googleapis_auth: ^1.4.1
    intl: ^0.18.1
    provider: ^6.0.5

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - google_fonts/
