// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK4rs7DfXuwOUk_HLPp8wA6fYOoCpX1_c',
    appId: '1:233945495575:web:49aef665cfd8436e2c8452',
    messagingSenderId: '233945495575',
    projectId: 'todo-app-396320',
    authDomain: 'todo-app-396320.firebaseapp.com',
    storageBucket: 'todo-app-396320.appspot.com',
    measurementId: 'G-D0J4BJXDMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC83cgGmmbstf9F-z6J6B-7CkdK831QJSU',
    appId: '1:233945495575:android:ae80405704b2cf992c8452',
    messagingSenderId: '233945495575',
    projectId: 'todo-app-396320',
    storageBucket: 'todo-app-396320.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Y04vS10ukz0rqiMYr55YaaztlPq6En8',
    appId: '1:233945495575:ios:bcb2eba7c1971ac12c8452',
    messagingSenderId: '233945495575',
    projectId: 'todo-app-396320',
    storageBucket: 'todo-app-396320.appspot.com',
    iosClientId: '233945495575-21fckbi5rrs5bbrua37gveamb2h0sc9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Y04vS10ukz0rqiMYr55YaaztlPq6En8',
    appId: '1:233945495575:ios:d111925e90595a6b2c8452',
    messagingSenderId: '233945495575',
    projectId: 'todo-app-396320',
    storageBucket: 'todo-app-396320.appspot.com',
    iosClientId: '233945495575-fqiu8pt86ngd6lc453u9dtu8qp07h193.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
